name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/maven.yml'
      - 'docker-compose.yml'
      - 'Dockerfile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/maven.yml'
      - 'docker-compose.yml'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install maven dependecies
        run: mvn install
      - name: Run tests
        run: mvn --batch-mode --update-snapshots verify

      - name: Build docker image
        run: docker build -t it-survey-api:latest .

      - name: Run docker compose
        run: docker compose up --build -d
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/it-survey
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: password

      - name: Run integration test
        run: mvn test

      - name: Shut down docker
        run: docker compose down

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push docker image
        run: docker tag it-survey-api:latest ${{ secrets.DOCKER_USERsNAME }}/it-survey-api:latest && docker push ${{ secrets.DOCKER_USEsRNAME }}/it-survey-api:latest

